BikesShop/Controllers/ShoppingCartController.cs
using BikesShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BikesShop.ViewModels;

namespace BikesShop.Controllers
{

   
    public class ShoppingCartController : Controller
    {
        BikeOnineShopDBContext storeDB = new BikeOnineShopDBContext();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            // Return the view
            return View(viewModel);
        }

        public ActionResult AddToCart(int id)
        {

            // Retrieve the album from the database
            var addedProduct = storeDB.Products
                .Single(P => P.Id == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedProduct);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string proName = storeDB.Carts
                .Single(item => item.RecordId == id).Product.Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(proName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }

        public ActionResult Checkout()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            var customer = (from cust in storeDB.Customers
                            where cust.Email == User.Identity.Name 
                            select new { cust.ID , cust.Name }).FirstOrDefault();

            int orderId = 1;

            var order = (from ord in storeDB.Orders
                         select new { ord.OrderNumber , ord.OrderDate }).OrderByDescending(a=>a.OrderDate).FirstOrDefault();

            if (order != null)
            {
                orderId = Int32.Parse(order.OrderNumber) + 1;
            }

            Order or = new Order();
            or.OrderNumber = orderId.ToString();
            or.Customer_Id = customer.ID;
            or.OrderDate = DateTime.Now;
            or.total = decimal.Parse(viewModel.CartTotal.ToString());
            or.Username = customer.Name;
            storeDB.Orders.Add(or);
            storeDB.SaveChanges();
            
            foreach (var item in viewModel.CartItems)
            {

                OrdersDetail od = new OrdersDetail();
                od.OrderNumber = orderId.ToString();
                od.ProductId = item.ProductId;
                od.Unitprice = decimal.Parse(item.Product.Price.ToString());
                od.Quantity = item.Count;
             
                storeDB.OrdersDetails.Add(od);
                storeDB.SaveChanges();

                for (int i = 0; i < item.Count; i++)
                {
                    RemoveFromCart(item.RecordId);
                }
            }
            return RedirectToAction("Index");
        }

    }
}

BikesShop/Controllers/StoreController.cs
using BikesShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BikesShop.Controllers
{
    public class StoreController : Controller
    {
        private BikeOnineShopDBContext db = new BikeOnineShopDBContext();

        // GET: Store
        public ActionResult Index()
        {
            return View();
        }

        //[HttpPost]
        //public ActionResult AddRate(Product pr, int Id)
        //{
        //    int rate = pr.ProductCommentRate.ProductRate.Rate;
        //    //invaled rate
        //    if (rate <= 0 || rate > 5 || rate.Equals(null))
        //        return RedirectToAction("Details", "Store", new { id = Id });

        //    int proId = Id;
        //    string customerEmail = User.Identity.Name;

        //    var customerId = (from c in db.Customers
        //                      where c.Email == customerEmail
        //                      select c).ToList();
        //    //add new rate to Product Rate table
        //    ProductRate ProRate = new ProductRate();
        //    int cId = customerId.FirstOrDefault().ID;
        //    var OldExistCustRate = (from d in db.ProductRates where d.CustomerId == cId select d).ToList();
        //    if (OldExistCustRate.FirstOrDefault() != null)
        //    {
        //        ProRate = db.ProductRates.Find(OldExistCustRate.FirstOrDefault().Id);
        //        db.ProductRates.Remove(ProRate);
        //        db.SaveChanges();
        //    }
        //    ProRate.CustomerId = customerId.FirstOrDefault().ID;
        //    ProRate.ProductId = proId;
        //    ProRate.RateDate = System.DateTime.Now;
        //    ProRate.Product = db.Products.Find(proId);
        //    ProRate.Customer = db.Customers.Find(customerId.FirstOrDefault().ID);
        //    ProRate.Rate = rate;
        //    db.ProductRates.Add(ProRate);
        //    db.SaveChanges();
        //    return RedirectToAction("Details", "Store", new { id = Id });
        //}

        //[HttpPost]
        //public ActionResult AddComment(Product pcr, string Command1, int Id)
        //{

        //    if (User.Identity.IsAuthenticated)
        //    {
        //        string comment = pcr.ProductCommentRate.CustomersComment.Comment.ToString();

        //        int proId = Id;

        //        string customerEmail = User.Identity.Name;

        //        var customerId = (from c in db.Customers
        //                          where c.Email == customerEmail
        //                          select c).ToList();
        //        CustomersComment cc = new CustomersComment();
        //        cc.Comment = comment;
        //        cc.CustomerId = customerId.FirstOrDefault().ID;
        //        cc.ProductId = proId;
        //        cc.CommentDate = System.DateTime.Now;
        //        cc.Customer = db.Customers.Find(customerId.FirstOrDefault().ID);
        //        cc.Product = db.Products.Find(proId);
        //        db.CustomersComments.Add(cc);
        //        db.SaveChanges();

        //        return RedirectToAction("Details", "Store", new { id = Id });
        //    }
        //    else
        //    {
        //        return RedirectToAction("Details", "Store", new { id = Id });
        //    }
        //}
        public ActionResult Details(int id)
        {
            var pro = db.Products.Find(id);
            if (User.Identity.IsAuthenticated)
            {
                var rateSum = (from rte in db.ProductRates
                               where rte.ProductId == pro.Id
                               select rte).ToList();
                if (rateSum.Count != 0)
                {
                    int total = 0;
                    foreach (var v in rateSum)
                    {
                        total += v.Rate;
                    }
                    var rateAvg = total / rateSum.Count;
                    if (pro.AverageRate.Equals(null) || pro.AverageRate == 0 || pro.AverageRate != rateAvg)
                    {
                        pro.AverageRate = rateAvg;
                    }

                    //get user id and average to show old customer rate
                    ///////////////////////////////////////////
                    string customerEmail = User.Identity.Name;

                    var customerId = (from c in db.Customers
                                      where c.Email == customerEmail
                                      select c).ToList();
                    int Oldrate;
                    int cId = customerId.FirstOrDefault().ID;
                    var OldExistCustRate = (from d in db.ProductRates where d.CustomerId == cId select d).ToList();
                    if (OldExistCustRate.FirstOrDefault() != null)
                    {
                        Oldrate = customerId.FirstOrDefault().ProductRates.FirstOrDefault().Rate;
                    }
                    else
                        Oldrate = 0;
                    if (Oldrate.Equals(null) || Oldrate == 0)
                        ViewData["OldRate"] = 0;
                    else
                        ViewData["OldRate"] = Oldrate;

                    /////////////////////////////////////////

                    ViewData["Average"] = rateAvg;
                    if (rateAvg > 0)
                        ViewBag.RateAverage = rateAvg.ToString();
                    else
                       ViewBag.RateAverage = 0;
                }

                else
                {
                    ViewData["Average"] = 0;
                    ViewData["OldRate"] = 0;

                    ViewBag.RateAverage = 0;

                }
            }
            else
            {
                var rateSum = (from rte in db.ProductRates
                               where rte.ProductId == pro.Id
                               select rte).ToList();
                if (rateSum.Count != 0)
                {
                    int total = 0;
                    foreach (var v in rateSum)
                    {
                        total += v.Rate;
                    }
                    var rateAvg = total / rateSum.Count;
                    if (pro.AverageRate.Equals(null) || pro.AverageRate == 0 || pro.AverageRate != rateAvg)
                    {
                        pro.AverageRate = rateAvg;
                    }
                    ViewData["OldRate"] = 0;
                    ViewData["Average"] = rateAvg;
                }
                else
                {
                    ViewData["Average"] = 0;
                    ViewData["OldRate"] = 0;

                    ViewBag.RateAverage = 0;
                }
            }
            return View(pro);
        }


        public ActionResult Browse(string genre)
        {

            var genreModel = db.Products.Include("Products")
                .Single(g => g.Name == genre);

            return View(genreModel);
        }

        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var categories = (from cat in db.Products select new { cat.Category }).ToList();


            return PartialView(categories);
        }
    }
}

BikesShop/Views/Store/Browse.cshtml
@model BikesShop.Models.Product
@{
    ViewBag.Title = "Browse Products";
}

<div class="genre">
    <h3><em>@Model.Name</em></h3>

    <ul id="product-list">
        @foreach(var v in Model.Products)
        {
            <li>
                <a href="@Url.Action("Details",new {id= v.Id})"></a>
                <img alt="@v.Name" src="@v.ImageName "/>
                <span>@v.Name</span>
            </li> 
        }
    </ul>
</div>

BikesShop/Views/Store/Details.cshtml
@model BikesShop.Models.Product
@{
    ViewBag.Title = "Product:" + Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center>
    <h2>@Model.Name</h2>
    <br />
    <p>
        <img src="@Url.Content("~/images/" + Model.ImageName)" alt="" style="width:600px; height:450px"/>
    </p>
</center>
<br />
<p class="text-danger">@ViewBag.NotLog</p>
<div id="product-details" style="margin-left:150px">

    <div class="col-md-12">
        <p>
            <h4 style="text-decoration:underline;font-style:italic">Name:</h4>
            @Model.Name
        </p>
        <p>
            <h4 style="text-decoration:underline;font-style:italic">Price:</h4>
            @Model.Price
        </p>
        <p>
        @*<p>
           
            <h4 style="text-decoration:underline;font-style:italic">Product Rate Average: </h4>
      
              @for (int properity = (Int32)@ViewData["Average"] ; properity > 0 ; properity--)
              {
                <span class="fa fa-star" style="color:#FFCC00"></span>


              }
            @for (int properity = 5-(Int32)@ViewData["Average"]; properity > 0; properity--)
            {
                <span class="fa  fa-star-o" style="color:#9A9379"></span>


            }
        </p>*@
        <p>
            <h4 style="text-decoration:underline;font-style:italic">Brief:</h4>
            @Model.Brief
        </p>
        <div class="row">
            <div class="w3_leave_comment">

                <div class="col-md-2">

                    <div>

                        @if (User.Identity.IsAuthenticated)
                        {

                            using (Html.BeginForm("AddToCart", "ShoppingCart", new { Id = Model.Id }))
                            {
                                <input type="submit" value="Add To Cart" title="@Model.Id" name="Command1" id="@Model.Id" class="btn btn-success" />

                            }

                        }
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <br />
            
            <div class="col-md-2">

                @*@if (User.Identity.IsAuthenticated)
                {
                    if (Model.ProductRates.Count > 0)
                    {
                        if (!Model.ProductRates.FirstOrDefault().CustomerId.Equals(null) || !Model.ProductRates.FirstOrDefault().CustomerId.Equals(0))

                        {
                            <p>Your Old Rate Was: (@ViewData["OldRate"])</p>

                            for (int properity = (Int32)@ViewData["OldRate"]; properity > 0; properity--)
                            {
                                <span class="fa fa-star" style="color:#FFCC00"></span>


                            }
                            for (int properity = 5 - (Int32)@ViewData["OldRate"]; properity > 0; properity--)
                            {
                                <span class="fa fa-star-o" style="color:#9A9379"></span>


                            }
                        }
                    }
                    using (Html.BeginForm("AddRate", "Store", new { Id = Model.Id }, FormMethod.Post))
                    {
                        @Html.EditorFor(mod => mod.ProductCommentRate.ProductRate.Rate, new { htmlAttributes = new { @class = "form-control" } })
                        <br />  <input type="submit" value="Add Rate" title="@Model.Id" name="Command1" id="@Model.Id" class="btn btn-success" />

                    }
                }*@
            </div>
        </div>
        <br />
       
    
    </div>
    
    <br />
   
      
    &nbsp;&nbsp;&nbsp;&nbsp;
</div>

<br />

BikesShop/Views/Store/GenreMenu.cshtml
@model IEnumerable<BikesShop.Models.Product>

<ul id="categories">
    @foreach (var genre in Model)
    {
        <li>
            @Html.ActionLink(genre.Name,
                "Browse", "Store",
                new { Genre = genre.Name }, null)
        </li>
    }
</ul>